import React, { useContext, useEffect } from 'react';
import { ShopContext } from '../context/Shopcontext';
import { useSearchParams } from 'react-router-dom';
import axios from 'axios';
import { toast } from 'react-toastify';

const Verify = () => {
    const { navigate, backendUrl, token, setCartItems } = useContext(ShopContext);
    const [searchParams] = useSearchParams();

    // Parse the query arguments generated by Stripe session redirection rules
    const success = searchParams.get('success');
    const orderId = searchParams.get('orderId');

    const verifyPayment = async () => {
        try {
            if (!token) return null;

            // Make request to your verifyStripe endpoint on the backend
            const response = await axios.post(
                backendUrl + '/api/order/verifyStripe', 
                { success, orderId }, 
                { headers: { token } }
            );

            if (response.data.success) {
                setCartItems({}); // Empty out local cart state cache cleanly
                toast.success(response.data.message || "Payment Successful!");
                navigate('/orders'); // Route to history view upon purchase confirmation
            } else {
                toast.error(response.data.message || "Payment Failed.");
                navigate('/cart'); // Send back to cart bucket loop if authorization breaks
            }

        } catch (error) {
            console.error(error);
            toast.error(error.response?.data?.message || error.message);
            navigate('/cart');
        }
    };

    useEffect(() => {
        verifyPayment();
    }, [token]);

    return (
        <div className='min-h-[60vh] flex flex-col items-center justify-center gap-4 border-t pt-24'>
            {/* Spinning Status Loader Graphic Element Matrix */}
            <div className='w-16 h-16 border-4 border-gray-200 border-t-black rounded-full animate-spin'></div>
            <p className='text-gray-500 font-medium text-sm tracking-widest uppercase animate-pulse mt-2'>
                Verifying Payment Status...
            </p>
        </div>
    );
};

export default Verify;